files:
  - source: /bookwyrm/templates
    ignore:
      - /bookwyrm/migrations
      - /bookwyrm/tests
      - /bookwyrm/middleware
    translation: /locale/%locale_with_underscore%/LC_MESSAGES/%locale_with_underscore%.po
    translate_content: 0
    translate_attributes: 0
    content_segmentation: 0
