version: '3'

services:
    db:
        image: postgres
        env_file: .env
        volumes:
          - pgdata:/var/lib/postgresql/data
        networks:
            - main
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        depends_on:
            - db
            - celery_worker
        networks:
            - main
    redis:
        image: redis
        env_file: .env
        ports:
          - "6379:6379"
        networks:
            - main
        restart: on-failure
    celery_worker:
        env_file: .env
        build: .
        networks:
            - main
        command: celery -A fr_celery worker -l info
        volumes:
            - .:/app
        depends_on:
            - db
            - redis
        restart: on-failure
    flower:
        image: mher/flower
        env_file: .env
        ports:
            - "5555:5555"
        restart: on-failure
volumes:
    pgdata:
networks:
    main:
