name: Accessibility Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Scan for accessibility issues
	uses: microsoft/accessibility-insights-action@v2
	with:
	  repo-token: ${{ secrets.GITHUB_TOKEN }}
	  site-dir: ${{ github.workspace }}/bookwyrm/templates
	  scan-url-relative-path: / # use // if windows agen

      - name: Upload report artifact
        uses: actions/upload-artifact@v2
        with:
          name: accessibility-reports
          path: ${{ github.workspace }}/_accessibility-reports
